{
 "title": "t___BlitzIndex_Analysis",
 "description": "Data of BlitzIndex",
 "tags": [
  "mssql",
  "sqlmonitor"
 ],
 "time": { "from": "now-2h", "to": "now" },
 "refresh": "15m",
 "templating": {
  "list": [
   { "name": "sqlmonitor_datasource", "label": "Data Source", "query": "mssql" },
   {
    "name": "server",
    "label": "Sql Instance",
    "query": "declare @sql nvarchar(max);\n\nset quoted_identifier off;\nset @sql = \"select distinct srvname = sql_instance from dbo.instance_details with (nolock)\nwhere is_available = 1 and is_enabled = 1\n\";\nset quoted_identifier off;\n\nexec dbo.sp_executesql @sql;"
   },
   { "name": "inventory_db", "label": "Inventory Database", "query": "SELECT DB_NAME()" },
   {
    "name": "is_local",
    "label": "Is Local SQL Instance",
    "query": "declare @sql_instance varchar(255); \nset @sql_instance = '$server';\nselect is_local = case when ( (CONVERT(varchar,SERVERPROPERTY('MachineName')) = @sql_instance ) \n\t\t\tor (CONVERT(varchar,SERVERPROPERTY('ServerName')) = @sql_instance )\n\t\t\t)  then 1 else 0 end"
   },
   {
    "name": "dba_db",
    "label": "DBA Database",
    "query": "declare @sql nvarchar(max);\ndeclare @sql_instance varchar(255);\nset @sql_instance = '$server';\n\nset quoted_identifier off;\nset @sql = \"select top 1 [database] from dbo.instance_details id\nwhere id.sql_instance = @sql_instance\n\";\nset quoted_identifier off;\n\nexec dbo.sp_executesql @sql, N'@sql_instance varchar(255)', @sql_instance;"
   },
   {
    "name": "ip",
    "label": "IP Address",
    "query": "declare @sql nvarchar(max);\ndeclare @params nvarchar(max);\ndeclare @sql_instance varchar(255);\n\nset @sql_instance = '$server';\nset @params = N'@sql_instance varchar(255)';\n\nset quoted_identifier off;\nset @sql = \"select CONVERT(varchar,  CONNECTIONPROPERTY('local_net_address') ) as [ip];\"\nset quoted_identifier on;\n\n--if (@sql_instance = SERVERPROPERTY('SERVERNAME'))\nif ($is_local = 1)\n  exec dbo.sp_executesql @sql --, @params, @sql_instance;\nelse\n  exec [$server].[$dba_db].dbo.sp_executesql @sql --, @params, @sql_instance;"
   },
   {
    "name": "fqdn",
    "label": "FQDN",
    "query": "declare @sql nvarchar(max);\ndeclare @params nvarchar(max);\ndeclare @sql_instance varchar(255);\n\nset @sql_instance = '$server';\nset @params = N'@sql_instance varchar(255)';\n\nset quoted_identifier off;\nset @sql = \"declare @fqdn nvarchar(100);\nexec usp_extended_results @fqdn = @fqdn output;\n\nselect case when default_domain() = 'WORKGROUP' then 'WORKGROUP' ELSE @fqdn END\n\"\nset quoted_identifier on;\n\n--if (@sql_instance = SERVERPROPERTY('SERVERNAME'))\nif ($is_local = 1)\n  exec dbo.sp_executesql @sql --, @params, @sql_instance;\nelse\n  exec [$server].[$dba_db].dbo.sp_executesql @sql --, @params, @sql_instance;"
   },
   {
    "name": "collection_time_utc",
    "label": "Collection Time UTC",
    "query": "declare @sql nvarchar(max);\ndeclare @params nvarchar(max);\ndeclare @sql_instance varchar(255);\n--declare @perfmon_host_name varchar(255);\ndeclare @start_time_utc datetime2;\ndeclare @end_time_utc datetime2;\n--declare @delta_minutes int;\n\nset @sql_instance = '$server';\n--set @perfmon_host_name = '$perfmon_host_name';\nset @start_time_utc = $__timeFrom();\nset @end_time_utc = $__timeTo();\n--set @delta_minutes = $cpu_delta_minutes;\nset @params = N'@start_time_utc datetime2, @end_time_utc datetime2';\n\nset quoted_identifier off;\nset @sql = \"\nset nocount on;\nselect top 1 DATEADD(mi, DATEDIFF(mi, getdate(), getutcdate()), run_datetime )\nfrom $blitzindex_table_name\norder by run_datetime desc\n\"\nset quoted_identifier on;\n\n--if (@sql_instance = SERVERPROPERTY('SERVERNAME'))\nif ($is_local = 1)\n  exec dbo.sp_executesql @sql, @params, @start_time_utc, @end_time_utc;\nelse\n  exec [$server].[$dba_db].dbo.sp_executesql @sql, @params, @start_time_utc, @end_time_utc;"
   },
   {
    "name": "sql_schedulers",
    "label": "SQL Schedulers",
    "query": "declare @sql nvarchar(max);\ndeclare @params nvarchar(max);\ndeclare @sql_instance varchar(255);\ndeclare @perfmon_host_name varchar(255);\n\nset @sql_instance = '$server';\n--set @perfmon_host_name = '$perfmon_host_name';\nset @params = N'@perfmon_host_name varchar(255)';\n\nset quoted_identifier off;\nset @sql = \"select count(*) as counts from sys.dm_os_schedulers dos where status = 'VISIBLE ONLINE' and is_online = 1;\"\nset quoted_identifier on;\n\n--if (@sql_instance = SERVERPROPERTY('SERVERNAME'))\nif ($is_local = 1)\n  exec dbo.sp_executesql @sql , @params, @perfmon_host_name;\nelse\n  exec [$server].[$dba_db].dbo.sp_executesql @sql , @params, @perfmon_host_name;"
   },
   {
    "name": "sqlserver_start_time_utc",
    "label": "SqlInstance Start Time UTC",
    "query": "declare @sql nvarchar(max);\ndeclare @params nvarchar(max);\ndeclare @sql_instance varchar(255);\ndeclare @perfmon_host_name varchar(255);\n\nset @sql_instance = '$server';\nset @perfmon_host_name = '$perfmon_host_name';\nset @params = N'@perfmon_host_name varchar(255)';\n\nset quoted_identifier off;\nset @sql = \"select DATEADD(mi, DATEDIFF(mi, getdate(), getutcdate()), sqlserver_start_time) from sys.dm_os_sys_info as osi;\"\nset quoted_identifier on;\n\n--if (@sql_instance = SERVERPROPERTY('SERVERNAME'))\nif ($is_local = 1)\n  exec dbo.sp_executesql @sql , @params, @perfmon_host_name;\nelse\n  exec [$server].[$dba_db].dbo.sp_executesql @sql , @params, @perfmon_host_name;"
   },
   {
    "name": "disk_drive",
    "label": "Disk Drive",
    "query": "declare @sql nvarchar(max);\ndeclare @params nvarchar(max);\ndeclare @sql_instance varchar(255);\ndeclare @perfmon_host_name varchar(255);\n\nset @sql_instance = '$server';\n--set @perfmon_host_name = '$perfmon_host_name';\nset @params = N'@perfmon_host_name varchar(255)';\n\nset quoted_identifier off;\nset @sql = \"select ds.disk_volume as disk_drive\n\tfrom dbo.disk_space ds\n\twhere ds.collection_time_utc = (select max(i.collection_time_utc) from dbo.disk_space i)\n\tunion all\n\tselect '__All__' as disk_drive\n\torder by disk_drive\"\nset quoted_identifier on;\n\n--if (@sql_instance = SERVERPROPERTY('SERVERNAME'))\nif ($is_local = 1)\n  exec dbo.sp_executesql @sql , @params, @perfmon_host_name;\nelse\n  exec [$server].[$dba_db].dbo.sp_executesql @sql , @params, @perfmon_host_name;"
   },
   {
    "name": "database",
    "label": "Database",
    "query": "declare @sql nvarchar(max);\ndeclare @params nvarchar(max);\ndeclare @sql_instance varchar(255);\ndeclare @perfmon_host_name varchar(255);\n\nset @sql_instance = '$server';\n--set @perfmon_host_name = '$perfmon_host_name';\nset @params = N'@perfmon_host_name varchar(255)';\n\nset quoted_identifier off;\nset @sql = \"select name from sys.databases d where d.state_desc = 'ONLINE' union all select '__All__' as name order by name;\"\nset quoted_identifier on;\n\n--if (@sql_instance = SERVERPROPERTY('SERVERNAME'))\nif ($is_local = 1)\n  exec dbo.sp_executesql @sql , @params, @perfmon_host_name;\nelse\n  exec [$server].[$dba_db].dbo.sp_executesql @sql , @params, @perfmon_host_name;"
   },
   { "name": "blitzindex_table_name", "label": "BlitzIndex Table", "query": "dbo.BlitzIndex" },
   { "name": "delta_days_threshold", "label": "Delta Days", "query": "5,10,15,20,30,60,90,180,365" },
   { "name": "page_no", "label": "Page No", "query": "1" },
   { "name": "page_size", "label": "Page Size", "query": "100" },
   { "name": "table_name", "label": "Table Name" },
   { "name": "blitzindex_mode0_table_name", "label": "BlitzIndex Table", "query": "dbo.BlitzIndex_Mode0" },
   { "name": "blitzindex_mode1_table_name", "label": "BlitzIndex Table", "query": "dbo.BlitzIndex_Mode1" },
   { "name": "blitzindex_mode4_table_name", "label": "BlitzIndex Table", "query": "dbo.BlitzIndex_Mode4" }
  ]
 },
 "panels": [
  {
   "title": "Database Size Summary -- FILTERED - Paginated - Page No {$page_no} - Page Size {$page_size}  ____@ ____${collection_time_utc:date:YYYY-MM-DD HH.mm}_____ - [$fqdn] - [$ip]",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 0 },
   "collapsed": true,
   "panels": [
    {
     "title": "Database Size Summary -- FILTERED - Paginated - Page No {$page_no} - Page Size {$page_size}  ____@ ____${collection_time_utc:date:YYYY-MM-DD HH.mm}_____ - [$fqdn] - [$ip]",
     "type": "table",
     "description": "exec sp_BlitzIndex @Mode = 2",
     "gridPos": { "h": 15, "w": 24, "x": 0, "y": 1 },
     "targets": [
      {
       "rawSql": "declare @sql nvarchar(max);\ndeclare @params nvarchar(max);\ndeclare @sql_instance varchar(255) = '$server';\ndeclare @start_time_utc datetime2;\ndeclare @end_time_utc datetime2;\ndeclare @delta_days_threshold int = ${delta_days_threshold};\ndeclare @buffer_days int = 2;\ndeclare @database varchar(255) = '$database';\ndeclare @page_no int;\ndeclare @page_size int;\ndeclare @table_name varchar(255);\n\nset @database = case when ltrim(rtrim(@database)) = '__All__' then null else @database end;\nset @start_time_utc = $__timeFrom();\nset @end_time_utc = $__timeTo();\nif len(ltrim(rtrim('$page_no'))) > 0 and (case when '$page_no' like '%[^0-9.]%' then 'invalid' when '$page_no' like '%.%.%' then 'invalid' else 'valid' end) = 'valid'\n  set @page_no = convert(int,ltrim(rtrim('$page_no')));\nif len(ltrim(rtrim('$page_size'))) > 0 and (case when '$page_size' like '%[^0-9.]%' then 'invalid' when '$page_size' like '%.%.%' then 'invalid' else 'valid' end) = 'valid'\n  set @page_size = convert(int,ltrim(rtrim('$page_size')));\nif len(ltrim(rtrim('$table_name'))) > 0\n  set @table_name = '$table_name'\n\nset @params = N'@database varchar(255), @delta_days_threshold int, @buffer_days int, @page_no int, @page_size int, @table_name varchar(255)';\n\nset quoted_identifier off;\nset @sql = \"/* SQLMonitor - BlitzIndex Analysis - 0 Delta Rows */\nset nocount on;\n\nselect \trun_datetime = DATEADD(mi, DATEDIFF(mi, getdate(), getutcdate()), bi.run_datetime),\n\t\t\t\tbi.[database_name], bi.[object_count], bi.[reserved_gb], \n        bi.[reserved_lob_gb], bi.[reserved_row_overflow_gb], bi.[clustered_table_count], \n        bi.[clustered_table_gb], bi.[nc_index_count], bi.[nc_index_gb], \n        bi.[table_nc_index_ratio], bi.[heap_count], bi.[heap_gb], bi.[partioned_table_count], \n        bi.[partioned_nc_count], bi.[partioned_gb], bi.[filtered_index_count], \n        bi.[indexed_view_count], bi.[max_table_row_count], bi.[max_table_gb], \n        bi.[max_nc_index_gb], bi.[table_count_over_1gb], bi.[table_count_over_10gb], \n        bi.[table_count_over_100gb], bi.[nc_index_count_over_1gb], bi.[nc_index_count_over_10gb], \n        bi.[nc_index_count_over_100gb], bi.[min_create_date], \n        [max_create_date] = DATEADD(mi, DATEDIFF(mi, getdate(), getutcdate()), bi.max_create_date), \n        [max_modify_date] = DATEADD(mi, DATEDIFF(mi, getdate(), getutcdate()), bi.max_modify_date)\nfrom ${blitzindex_mode1_table_name} bi\nwhere bi.run_datetime = (select max(i.run_datetime) from ${blitzindex_mode1_table_name} i)\n\"+(case when @database is null then '-- ' else '' end)+\"and bi.database_name = @database\norder by bi.reserved_gb desc, bi.object_count desc, bi.database_name\noffset ((@page_no-1)*@page_size) rows fetch next @page_size rows only;\n\"\nset quoted_identifier on;\n\nif ($is_local = 1)\n  exec dbo.sp_executesql @sql, @params, @database, @delta_days_threshold, @buffer_days, @page_no, @page_size, @table_name;\nelse\n  exec [$server].[$dba_db].dbo.sp_executesql @sql, @params, @database, @delta_days_threshold, @buffer_days, @page_no, @page_size, @table_name;"
      }
     ]
    }
   ]
  },
  {
   "title": "Tables with \"Zero Growth\" in Last __\"$delta_days_threshold\"__Days -- FILTERED - Paginated - Page No {$page_no} - Page Size {$page_size}  ____@ ____${collection_time_utc:date:YYYY-MM-DD HH.mm}_____ - [$fqdn] - [$ip]",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 1 },
   "collapsed": true,
   "targets": [
    {}
   ],
   "panels": [
    {
     "title": "Tables with 0 Delta rows in Last __\"$delta_days_threshold\"__Days -- FILTERED - Paginated - Page No {$page_no} - Page Size {$page_size}  ____@ ____${collection_time_utc:date:YYYY-MM-DD HH.mm}",
     "type": "table",
     "description": "exec sp_BlitzIndex @Mode = 2",
     "gridPos": { "h": 18, "w": 24, "x": 0, "y": 2 },
     "targets": [
      {
       "rawSql": "declare @sql nvarchar(max);\ndeclare @params nvarchar(max);\ndeclare @sql_instance varchar(255) = '$server';\ndeclare @start_time_utc datetime2;\ndeclare @end_time_utc datetime2;\ndeclare @delta_days_threshold int = ${delta_days_threshold};\ndeclare @buffer_days int = 2;\ndeclare @database varchar(255) = '$database';\ndeclare @page_no int;\ndeclare @page_size int;\ndeclare @table_name varchar(255);\n\nset @database = case when ltrim(rtrim(@database)) = '__All__' then null else @database end;\nset @start_time_utc = $__timeFrom();\nset @end_time_utc = $__timeTo();\nif len(ltrim(rtrim('$page_no'))) > 0 and (case when '$page_no' like '%[^0-9.]%' then 'invalid' when '$page_no' like '%.%.%' then 'invalid' else 'valid' end) = 'valid'\n  set @page_no = convert(int,ltrim(rtrim('$page_no')));\nif len(ltrim(rtrim('$page_size'))) > 0 and (case when '$page_size' like '%[^0-9.]%' then 'invalid' when '$page_size' like '%.%.%' then 'invalid' else 'valid' end) = 'valid'\n  set @page_size = convert(int,ltrim(rtrim('$page_size')));\nif len(ltrim(rtrim('$table_name'))) > 0\n  set @table_name = '$table_name'\n\nset @params = N'@database varchar(255), @delta_days_threshold int, @buffer_days int, @page_no int, @page_size int, @table_name varchar(255)';\n\nset quoted_identifier off;\nset @sql = \"/* SQLMonitor - BlitzIndex Analysis - 0 Delta Rows */\nset nocount on;\n\nif object_id('tempdb..#delta_tables') is not null\n\tdrop table #delta_tables;\nselect  [database_name], [schema_name], [table_name]\n\t\t--,total_rows_max = max(total_rows)\n\t\t--,total_rows_min = min(total_rows)\n\t\t--,total_rows_avg = avg(total_rows)\n\t\t--,days_count = datediff(day,min(run_datetime),max(run_datetime))\n\t\t,total_reserved_GB = max(convert(numeric(20,2),bi.total_reserved_MB/1024.0))\ninto #delta_tables\nfrom ${blitzindex_table_name} bi\nwhere bi.run_datetime >= dateadd(day,-(@delta_days_threshold+@buffer_days),getdate())\nand index_id <= 1\n\"+(case when @database is null then '-- ' else '' end)+\"and bi.database_name = @database\n\"+(case when @table_name is null then '-- ' else '' end)+\"and bi.table_name like ('%'+@table_name+'%')\ngroup by [database_name], [schema_name], [table_name]\nhaving min(total_rows) = max(total_rows) and max(total_rows) = avg(total_rows)\n\tand datediff(day,min(run_datetime),max(run_datetime)) > @delta_days_threshold\norder by total_reserved_GB desc\noffset ((@page_no-1)*@page_size) rows fetch next @page_size rows only;\n\nselect \t--collection_time = DATEADD(mi, DATEDIFF(mi, getdate(), getutcdate()), bi.run_datetime),\n\t\t\t\tbi.database_name, [object_name] = quotename(bi.schema_name)+'.'+quotename(bi.table_name), \n\t\t\t\t/* bi.index_name, bi.object_type, */ \n\t\t\t\tbi.index_size_summary, bi.index_definition,\n\t\t\t\tbi.index_usage_summary, bi.index_op_stats, --bi.total_rows, bi.total_reserved_MB, bi.total_reserved_LOB_MB,\n\t\t\t\tbi.data_compression_desc, bi.create_date, bi.more_info\nfrom ${blitzindex_table_name} bi\ninner join #delta_tables dt\n\ton bi.run_datetime = (select max(i.run_datetime) from ${blitzindex_table_name} i)\n\tand bi.database_name = dt.database_name and bi.schema_name = dt.schema_name and bi.table_name = dt.table_name\n\tand bi.index_id <= 1\norder by bi.total_reserved_MB desc, bi.total_rows desc\n\"\nset quoted_identifier on;\n\nif ($is_local = 1)\n  exec dbo.sp_executesql @sql, @params, @database, @delta_days_threshold, @buffer_days, @page_no, @page_size, @table_name;\nelse\n  exec [$server].[$dba_db].dbo.sp_executesql @sql, @params, @database, @delta_days_threshold, @buffer_days, @page_no, @page_size, @table_name;"
      }
     ]
    }
   ]
  },
  {
   "title": "Tables with \"Highest Growth\" in Last __\"$delta_days_threshold\"__Days -- FILTERED - Paginated - Page No {$page_no} - Page Size {$page_size}  ____@ ____${collection_time_utc:date:YYYY-MM-DD HH.mm}_____ - [$fqdn] - [$ip]",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 2 },
   "collapsed": true,
   "panels": [
    {
     "title": "Tables with \"Highest Growth\" in Last __\"$delta_days_threshold\"__Days -- FILTERED - Paginated - Page No {$page_no} - Page Size {$page_size}  ____@ ____${collection_time_utc:date:YYYY-MM-DD HH.mm}_____ - [$fqdn] - [$ip]",
     "type": "table",
     "description": "exec sp_BlitzIndex @Mode = 2",
     "gridPos": { "h": 18, "w": 24, "x": 0, "y": 3 },
     "targets": [
      {
       "rawSql": "declare @sql nvarchar(max);\ndeclare @params nvarchar(max);\ndeclare @sql_instance varchar(255) = '$server';\ndeclare @start_time_utc datetime2;\ndeclare @end_time_utc datetime2;\ndeclare @delta_days_threshold int = ${delta_days_threshold};\ndeclare @buffer_days int = 2;\ndeclare @database varchar(255) = '$database';\ndeclare @page_no int;\ndeclare @page_size int;\ndeclare @table_name varchar(255);\n\nset @database = case when ltrim(rtrim(@database)) = '__All__' then null else @database end;\nset @start_time_utc = $__timeFrom();\nset @end_time_utc = $__timeTo();\nif len(ltrim(rtrim('$page_no'))) > 0 and (case when '$page_no' like '%[^0-9.]%' then 'invalid' when '$page_no' like '%.%.%' then 'invalid' else 'valid' end) = 'valid'\n  set @page_no = convert(int,ltrim(rtrim('$page_no')));\nif len(ltrim(rtrim('$page_size'))) > 0 and (case when '$page_size' like '%[^0-9.]%' then 'invalid' when '$page_size' like '%.%.%' then 'invalid' else 'valid' end) = 'valid'\n  set @page_size = convert(int,ltrim(rtrim('$page_size')));\nif len(ltrim(rtrim('$table_name'))) > 0\n  set @table_name = '$table_name'\n\nset @params = N'@database varchar(255), @delta_days_threshold int, @buffer_days int, @page_no int, @page_size int, @table_name varchar(255)';\n\nset quoted_identifier off;\nset @sql = \"/* SQLMonitor - BlitzIndex Analysis - 0 Delta Rows */\nset nocount on;\n\nif object_id('tempdb..#delta_tables') is not null\n\tdrop table #delta_tables;\nselect  [database_name], [schema_name], [table_name]\n\t\t--,total_rows_max = max(total_rows)\n\t\t--,total_rows_min = min(total_rows)\n\t\t--,total_rows_avg = avg(total_rows)\n\t\t--,days_count = datediff(day,min(run_datetime),max(run_datetime))\n\t\t,total_reserved_GB = max(convert(numeric(20,2),bi.total_reserved_MB/1024.0))\n\t\t,total_growth_mb = MAX(total_reserved_MB)-MIN(total_reserved_MB)\ninto #delta_tables\nfrom ${blitzindex_table_name} bi\nwhere bi.run_datetime >= dateadd(day,-(@delta_days_threshold+@buffer_days),getdate())\nand index_id <= 1\n\"+(case when @database is null then '-- ' else '' end)+\"and bi.database_name = @database\n\"+(case when @table_name is null then '-- ' else '' end)+\"and bi.table_name like ('%'+@table_name+'%')\ngroup by [database_name], [schema_name], [table_name]\nhaving (max(total_reserved_MB) - min(total_reserved_MB)) > 0\n\tand datediff(day,min(run_datetime),max(run_datetime)) > @delta_days_threshold\norder by (MAX(total_reserved_MB)-MIN(total_reserved_MB)) DESC, total_reserved_GB desc\noffset ((@page_no-1)*@page_size) rows fetch next @page_size rows only;\n\nselect \t--collection_time = DATEADD(mi, DATEDIFF(mi, getdate(), getutcdate()), bi.run_datetime),\n\t\t\t\tbi.database_name, [object_name] = quotename(bi.schema_name)+'.'+quotename(bi.table_name), \n\t\t\t\t/* bi.index_name, bi.object_type, */ \n\t\t\t\tdt.total_growth_mb, bi.index_size_summary, bi.index_definition,\n\t\t\t\tbi.index_usage_summary, bi.index_op_stats, --bi.total_rows, bi.total_reserved_MB, bi.total_reserved_LOB_MB,\n\t\t\t\tbi.data_compression_desc, bi.create_date, bi.more_info\nfrom ${blitzindex_table_name} bi\ninner join #delta_tables dt\n\ton bi.run_datetime = (select max(i.run_datetime) from ${blitzindex_table_name} i)\n\tand bi.database_name = dt.database_name and bi.schema_name = dt.schema_name and bi.table_name = dt.table_name\n\tand bi.index_id <= 1\norder by dt.total_growth_mb desc, bi.total_reserved_MB desc, bi.total_rows desc\n\"\nset quoted_identifier on;\n\nif ($is_local = 1)\n  exec dbo.sp_executesql @sql, @params, @database, @delta_days_threshold, @buffer_days, @page_no, @page_size, @table_name;\nelse\n  exec [$server].[$dba_db].dbo.sp_executesql @sql, @params, @database, @delta_days_threshold, @buffer_days, @page_no, @page_size, @table_name;"
      }
     ]
    }
   ]
  },
  {
   "title": "High Priority Recommendations -- FILTERED - Paginated - Page No {$page_no} - Page Size {$page_size}  ____@ ____${collection_time_utc:date:YYYY-MM-DD HH.mm}_____ - [$fqdn] - [$ip]",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 3 },
   "collapsed": true,
   "panels": [
    {
     "title": "High Priority Recommendations -- FILTERED - Paginated - Page No {$page_no} - Page Size {$page_size}  ____@ ____${collection_time_utc:date:YYYY-MM-DD HH.mm}_____ - [$fqdn] - [$ip]",
     "type": "table",
     "description": "exec sp_BlitzIndex @Mode = 2",
     "gridPos": { "h": 17, "w": 24, "x": 0, "y": 4 },
     "targets": [
      {
       "rawSql": "declare @sql nvarchar(max);\ndeclare @params nvarchar(max);\ndeclare @sql_instance varchar(255) = '$server';\ndeclare @start_time_utc datetime2;\ndeclare @end_time_utc datetime2;\ndeclare @delta_days_threshold int = ${delta_days_threshold};\ndeclare @buffer_days int = 2;\ndeclare @database varchar(255) = '$database';\ndeclare @page_no int;\ndeclare @page_size int;\ndeclare @table_name varchar(255);\n\nset @database = case when ltrim(rtrim(@database)) = '__All__' then null else @database end;\nset @start_time_utc = $__timeFrom();\nset @end_time_utc = $__timeTo();\nif len(ltrim(rtrim('$page_no'))) > 0 and (case when '$page_no' like '%[^0-9.]%' then 'invalid' when '$page_no' like '%.%.%' then 'invalid' else 'valid' end) = 'valid'\n  set @page_no = convert(int,ltrim(rtrim('$page_no')));\nif len(ltrim(rtrim('$page_size'))) > 0 and (case when '$page_size' like '%[^0-9.]%' then 'invalid' when '$page_size' like '%.%.%' then 'invalid' else 'valid' end) = 'valid'\n  set @page_size = convert(int,ltrim(rtrim('$page_size')));\nif len(ltrim(rtrim('$table_name'))) > 0\n  set @table_name = '$table_name'\n\nset @params = N'@database varchar(255), @delta_days_threshold int, @buffer_days int, @page_no int, @page_size int, @table_name varchar(255)';\n\nset quoted_identifier off;\nset @sql = \"/* SQLMonitor - BlitzIndex Analysis - 0 Delta Rows */\nset nocount on;\n\nselect \trun_datetime = DATEADD(mi, DATEDIFF(mi, getdate(), getutcdate()), bi.run_datetime),\n\t\t\t\tbi.priority, bi.finding, bi.database_name, bi.details,\n\t\t    bi.index_definition, bi.secret_columns, bi.index_usage_summary, bi.index_size_summary,\n\t\t    bi.more_info, bi.url, bi.total_forwarded_fetch_count, bi.create_tsql\nfrom ${blitzindex_mode0_table_name} bi\nwhere bi.run_datetime = (select max(i.run_datetime) from ${blitzindex_mode0_table_name} i)\n\"+(case when @database is null then '-- ' else '' end)+\"and (bi.database_name = @database or bi.priority = -1)\n\"+(case when @table_name is null then '-- ' else '' end)+\"and (bi.more_info like ('%'+@table_name+'%') or bi.priority = -1)\norder by bi.priority asc\noffset ((@page_no-1)*@page_size) rows fetch next @page_size rows only;\n\"\nset quoted_identifier on;\n\nif ($is_local = 1)\n  exec dbo.sp_executesql @sql, @params, @database, @delta_days_threshold, @buffer_days, @page_no, @page_size, @table_name;\nelse\n  exec [$server].[$dba_db].dbo.sp_executesql @sql, @params, @database, @delta_days_threshold, @buffer_days, @page_no, @page_size, @table_name;"
      }
     ]
    }
   ]
  },
  {
   "title": "All Recommendations -- FILTERED - Paginated - Page No {$page_no} - Page Size {$page_size}  ____@ ____${collection_time_utc:date:YYYY-MM-DD HH.mm}_____ - [$fqdn] - [$ip]",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 4 },
   "collapsed": true,
   "panels": [
    {
     "title": "All Recommendations -- FILTERED - Paginated - Page No {$page_no} - Page Size {$page_size}  ____@ ____${collection_time_utc:date:YYYY-MM-DD HH.mm}_____ - [$fqdn] - [$ip]",
     "type": "table",
     "description": "exec sp_BlitzIndex @Mode = 2",
     "gridPos": { "h": 17, "w": 24, "x": 0, "y": 5 },
     "targets": [
      {
       "rawSql": "declare @sql nvarchar(max);\ndeclare @params nvarchar(max);\ndeclare @sql_instance varchar(255) = '$server';\ndeclare @start_time_utc datetime2;\ndeclare @end_time_utc datetime2;\ndeclare @delta_days_threshold int = ${delta_days_threshold};\ndeclare @buffer_days int = 2;\ndeclare @database varchar(255) = '$database';\ndeclare @page_no int;\ndeclare @page_size int;\ndeclare @table_name varchar(255);\n\nset @database = case when ltrim(rtrim(@database)) = '__All__' then null else @database end;\nset @start_time_utc = $__timeFrom();\nset @end_time_utc = $__timeTo();\nif len(ltrim(rtrim('$page_no'))) > 0 and (case when '$page_no' like '%[^0-9.]%' then 'invalid' when '$page_no' like '%.%.%' then 'invalid' else 'valid' end) = 'valid'\n  set @page_no = convert(int,ltrim(rtrim('$page_no')));\nif len(ltrim(rtrim('$page_size'))) > 0 and (case when '$page_size' like '%[^0-9.]%' then 'invalid' when '$page_size' like '%.%.%' then 'invalid' else 'valid' end) = 'valid'\n  set @page_size = convert(int,ltrim(rtrim('$page_size')));\nif len(ltrim(rtrim('$table_name'))) > 0\n  set @table_name = '$table_name'\n\nset @params = N'@database varchar(255), @delta_days_threshold int, @buffer_days int, @page_no int, @page_size int, @table_name varchar(255)';\n\nset quoted_identifier off;\nset @sql = \"/* SQLMonitor - BlitzIndex Analysis - 0 Delta Rows */\nset nocount on;\n\nselect \trun_datetime = DATEADD(mi, DATEDIFF(mi, getdate(), getutcdate()), bi.run_datetime),\n\t\t\t\tbi.priority, bi.finding, bi.database_name, bi.details,\n\t\t    bi.index_definition, bi.secret_columns, bi.index_usage_summary, bi.index_size_summary,\n\t\t    bi.more_info, bi.url, bi.create_tsql\nfrom ${blitzindex_mode4_table_name} bi\nwhere bi.run_datetime = (select max(i.run_datetime) from ${blitzindex_mode4_table_name} i)\n\"+(case when @database is null then '-- ' else '' end)+\"and (bi.database_name = @database or bi.priority = -1)\n\"+(case when @table_name is null then '-- ' else '' end)+\"and (bi.more_info like ('%'+@table_name+'%') or bi.priority = -1)\norder by bi.priority asc\noffset ((@page_no-1)*@page_size) rows fetch next @page_size rows only;\n\"\nset quoted_identifier on;\n\nif ($is_local = 1)\n  exec dbo.sp_executesql @sql, @params, @database, @delta_days_threshold, @buffer_days, @page_no, @page_size, @table_name;\nelse\n  exec [$server].[$dba_db].dbo.sp_executesql @sql, @params, @database, @delta_days_threshold, @buffer_days, @page_no, @page_size, @table_name;"
      }
     ]
    }
   ]
  },
  {
   "title": "All INDEX -- FILTERED - Paginated - Page No {$page_no} - Page Size {$page_size}  ____@ ____${collection_time_utc:date:YYYY-MM-DD HH.mm}_____ - [$fqdn] - [$ip]",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 5 },
   "collapsed": true,
   "panels": [
    {
     "title": "All INDEX -- FILTERED - Paginated - Page No {$page_no} - Page Size {$page_size}  ____@ ____${collection_time_utc:date:YYYY-MM-DD HH.mm}_____ - [$fqdn] - [$ip]",
     "type": "table",
     "description": "exec sp_BlitzIndex @Mode = 2",
     "gridPos": { "h": 18, "w": 24, "x": 0, "y": 6 },
     "targets": [
      {
       "rawSql": "declare @sql nvarchar(max);\ndeclare @params nvarchar(max);\ndeclare @sql_instance varchar(255) = '$server';\ndeclare @start_time_utc datetime2;\ndeclare @end_time_utc datetime2;\ndeclare @delta_days_threshold int = ${delta_days_threshold};\ndeclare @buffer_days int = 2;\ndeclare @database varchar(255) = '$database';\ndeclare @page_no int;\ndeclare @page_size int;\ndeclare @table_name varchar(255);\n\nset @database = case when ltrim(rtrim(@database)) = '__All__' then null else @database end;\nset @start_time_utc = $__timeFrom();\nset @end_time_utc = $__timeTo();\nif len(ltrim(rtrim('$page_no'))) > 0 and (case when '$page_no' like '%[^0-9.]%' then 'invalid' when '$page_no' like '%.%.%' then 'invalid' else 'valid' end) = 'valid'\n  set @page_no = convert(int,ltrim(rtrim('$page_no')));\nif len(ltrim(rtrim('$page_size'))) > 0 and (case when '$page_size' like '%[^0-9.]%' then 'invalid' when '$page_size' like '%.%.%' then 'invalid' else 'valid' end) = 'valid'\n  set @page_size = convert(int,ltrim(rtrim('$page_size')));\nif len(ltrim(rtrim('$table_name'))) > 0\n  set @table_name = '$table_name'\n\nset @params = N'@database varchar(255), @delta_days_threshold int, @buffer_days int, @page_no int, @page_size int, @table_name varchar(255)';\n\nset quoted_identifier off;\nset @sql = \"/* SQLMonitor - BlitzIndex Analysis - 0 Delta Rows */\nset nocount on;\n\nselect \trun_datetime = DATEADD(mi, DATEDIFF(mi, getdate(), getutcdate()), bi.run_datetime),\n\t\t\t\tbi.database_name, [object_name] = quotename(bi.schema_name)+'.'+quotename(bi.table_name), \n\t\t\t\t/* bi.index_name, bi.object_type, */ \n\t\t\t\tbi.index_size_summary, bi.index_definition,\n\t\t\t\tbi.index_usage_summary, bi.index_op_stats, --bi.total_rows, bi.total_reserved_MB, bi.total_reserved_LOB_MB,\n\t\t\t\tbi.data_compression_desc, bi.create_date, bi.more_info\nfrom ${blitzindex_table_name} bi\nwhere bi.run_datetime = (select max(i.run_datetime) from ${blitzindex_table_name} i)\n\"+(case when @database is null then '-- ' else '' end)+\"and bi.database_name = @database\n\"+(case when @table_name is null then '-- ' else '' end)+\"and bi.table_name like ('%'+@table_name+'%')\norder by bi.run_datetime, bi.id\noffset ((@page_no-1)*@page_size) rows fetch next @page_size rows only\n\"\nset quoted_identifier on;\n\nif ($is_local = 1)\n  exec dbo.sp_executesql @sql, @params, @database, @delta_days_threshold, @buffer_days, @page_no, @page_size, @table_name;\nelse\n  exec [$server].[$dba_db].dbo.sp_executesql @sql, @params, @database, @delta_days_threshold, @buffer_days, @page_no, @page_size, @table_name;"
      }
     ]
    }
   ]
  }
 ]
}